theme: jekyll-theme-minimal

description: Bookmark this to keep an eye on my booknotes updates!
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one